version: '3'

services:
    warehouse:
      image: postgres:14
      container_name: crypto_warehouse
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./database:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
        interval: 5s
        retries: 5
      restart: always
      ports:
        - "5432:5432"
    app:
      image: app
      depends_on:
        - warehouse
      container_name: crypto_app
      build:
        context: .
        dockerfile: Dockerfile.app
      volumes:
        - ./backend:/app/api
      environment:
        FLASK_ENV: production
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        REACT_APP_BACKEND_HOST: ${BACKEND_HOST}
        REACT_APP_BACKEND_PORT: ${BACKEND_PORT}
      ports:
        - "3000:3000"
